version: "3"
services:
  consultant-service:
    container_name: consultant-service
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: mvn
    #working_dir: /home/app # project is copied to this path in Dockerfile.
    command:
      - test # This will run all the tests including tests with test containers
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
      - TESTCONTAINERS_RYUK_DISABLED=true
      - SPRING_PROFILES_ACTIVE=docker
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock