version: '3'
services:
  eureka:
    build: ./eurekaserver
    ports:
    - "8761:8761"
  api-gateway:
    build: ./api-gateway
    ports:
    - "8081:8081"
    depends_on:
      - eureka
      - course-service
      - item-service
  course-service:
    build: ./course-service
    ports:
    - "8083:8083"
    depends_on:
      - eureka
  item-service:
    build: ./item-service
    ports:
    - "8082:8082"
    depends_on:
      - eureka
