version: "3"
services:
  docker_compose_test:
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: mvn
    #working_dir: /home/app # project is copied to this path in Dockerfile.
    command:
      - test
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
      - TESTCONTAINERS_RYUK_DISABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock