server:
  port: 8081
  servlet:
    context-path: /api-gateway
spring:
  application:
    name: api-gateway
feign:
  hystrix:
    enabled: false

#Actuator info
info:
  app: @name@
  version: @version@
  description: @description@