spring:
  application:
    name: api-gateway

server:
  port: 8081
  servlet:
    context-path: /api-gateway
    application-display-name: Mylms API Gateway

#Feign
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

#Eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000
eureka:
  instance:
    health-check-url-path: /actuator/health
    hostname: 192.168.99.100
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/

#Actuator info
info:
  app: @name@
  version: @version@
  description: @description@

course:
  service:
    url: http://localhost
    port: 8083

items:
  service:
    url: http://localhost
    port: 8082