server:
  port: 8081
  servlet:
    context-path: /api-gateway
    application-display-name: Mylms API Gateway
spring:
  application:
    name: api-gateway
feign:
  hystrix:
    enabled: false

#Eureka
eureka:
  instance:
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#Actuator info
info:
  app: @name@
  version: @version@
  description: @description@

course:
  service:
    url: http://localhost
    port: 8083

items:
  service:
    url: http://localhost
    port: 8082