server:
  port: 8081
  servlet:
    context-path: /api-gateway
    application-display-name: Mylms API Gateway
spring:
  application:
    name: api-gateway
feign:
  hystrix:
    enabled: false

#Eureka
eureka:
  client:
    service-url:
      default-zone: ${vcap.services.pwa-eureka-service.credentials.uri}/eureka/

#Actuator info
info:
  app: @name@
  version: @version@
  description: @description@

course:
  service:
    url: http://localhost
    port: 8083

items:
  service:
    url: http://localhost
    port: 8082