server:
  port: 8083
  servlet:
    context-path: /course-service
    application-display-name: Mylms Course Service
spring:
  application:
    name: course-service
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    #properties:
      #hibernate:
        #format_sql: true
        #dialect: org.hibernate.dialect.MySQL5Dialect
  #datasource:
  #  url: jdbc:mysql://localhost:3306/mylms2
  #  username: root
  #  password: root
  #  driver-class-name: com.mysql.jdbc.Driver

  # H2 DB
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org:hibernate:dialect:H2Dialect

feign:
  hysterix:
    enabled: false

#Eureka
eureka:
  instance:
    health-check-url-path: /actuator/health
    hostname: 192.168.99.100
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/

#Actuator info
info:
  app: @name@
  version: @version@
  description: @description@