server:
  port: 8083
  servlet:
    context-path: /course-service
    application-display-name: Mylms Course Service
spring:
  application:
    name: course-service
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    properties:
      hibernate:
        #format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/mylms2
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#Actuator info
info:
  app: @name@
  version: @version@
  description: @description@