spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testcontainer
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

projects:
  url: http://localhost:8081/api/projects