spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testcontainer
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

projects:
  url: http://localhost:8081/api/projects

localstack:
  #Default url for most services protocol://service-code.region-code.amazonaws.com
  sns:
    #endpoint: https://sns.eu-north-1.amazonaws.com
    endpoint: default
  #s3:
  #  endpoint: http://s3.%s.localstack.cloud:%d