spring:
  data:
    mongodb:
      database: testcontainers
      uri: mongodb://localhost:27017/testcontainers?readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    operations-sorter: method

# http://localhost:8080/v3/api-docs
# http://localhost:8080/v3/api-docs.yaml
# http://localhost:8080/swagger-ui.html

projects:
  url: http://localhost:8081/api/projects

localstack:
  #Default url for most services protocol://service-code.region-code.amazonaws.com
  sns:
    #endpoint: https://sns.eu-north-1.amazonaws.com
    endpoint: default
  #s3:
  #  endpoint: http://s3.%s.localstack.cloud:%d