# URLS
#XML: https://api.sl.se/api2/LineData.xml?model=jour&key=5da196d47f8f4e5facdb68d2e25b9eae
#JSON: https://api.sl.se/api2/LineData.json?model=jour&key=5da196d47f8f4e5facdb68d2e25b9eae

#Journey https://api.sl.se/api2/LineData.json?model=jour&key=7f0ec0b71b164c69b5484c2c8e30b9e8
#StopPoint https://api.sl.se/api2/LineData.json?model=stop&key=5da196d47f8f4e5facdb68d2e25b9eae

# Run on Tomcat port 7777
server:
  port: 7777

spring:
  application:
    name: trafiklab
    version: @version@

trafiklab:
  api:
    key: 936b30ea04354d7d8dd1337ee7602760
    url: https://api.sl.se/api2
