server:
  port: 8088
  #servlet:
  #  context-path: /item-service
spring:
  application:
    name: item-service


  # H2 DB
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org:hibernate:dialect:H2Dialect